a = [
    {'declaration_date': '20/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nVokalia',
     'active_ingredient_name': 'Mycophenolat mofetil 500mg', 'nd_dl': 'Mycophenolat mofetil 500mg',
     'gplh_gpnk': 'VN-17851-14', 'dosage_form': 'Viên nén bao phim', 'packaging_specifications': 'Hộp 10 vỉ x 10 viên',
     'DVT': 'Viên', 'price': '99.800'},
    {'declaration_date': '20/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nSCILIN M30 (30/70)',
     'active_ingredient_name': 'Recombinant human  insulin - 100IU/ml (30% solube insulin & 70% isophane insulin)',
     'nd_dl': '100 IU/ml', 'gplh_gpnk': 'QLSP-895-15', 'dosage_form': 'Hỗn dịch tiêm',
     'packaging_specifications': 'Hộp 1 lọ 10ml; Hộp 5 catridges x 3ml', 'DVT': 'Catridge', 'price': '145.000'},
    {'declaration_date': '20/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nCkdmyrept Tab. 500mg',
     'active_ingredient_name': 'Mycophenolat mofetil 500mg', 'nd_dl': 'Mycophenolat mofetil 500mg',
     'gplh_gpnk': 'VN-17851-14', 'dosage_form': 'Viên nén bao phim', 'packaging_specifications': 'Hộp 10 vỉ x 10 viên',
     'DVT': 'Viên', 'price': '53.800'}, {'declaration_date': '20/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nNeoamiyu',
                                         'active_ingredient_name': 'L-Isoleucine; L-Leucine; L-Lysine acetat; L-Methionine; L-Phenyllalanine; L-Threonine; L-Tryptophan; L-Valine; L-alanine, L-Arginine; L-Aspartic acid, L-Glutamic acid, L-Histidine, L-Proline,...',
                                         'nd_dl': 'Tổng lượng acid amin 12,2g Nồng độ acid amin 6,1% kl/tt',
                                         'gplh_gpnk': 'VN-16106-13', 'dosage_form': 'dung dịch truyền tĩnh mạch',
                                         'packaging_specifications': 'Túi 200ml', 'DVT': 'Túi', 'price': '116.258'},
    {'declaration_date': '20/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nMorihepamin',
     'active_ingredient_name': 'Mỗi 200ml có chứa L-Isoleucine 1,840g; L-Leucine 1,890g; L-Lysine acetate 0,790g; L-Methionine 0,088g; L-Phenylalamine 0,060g; L-Threonine 0,428g; L-Tryptophan 0,140g; L-Valine 1,780g; L-Alanine 1,680g; L-Arginine 3,074g; L-Aspartic acid 0,040g; L-Histidine 0,620g; L-Proline 1,060g; L-Serine 0,520g; L-Tyrosine 0,080g; Glycine 1,080g',
     'nd_dl': 'NULL', 'gplh_gpnk': 'VN-17215-13', 'dosage_form': 'Dung dịch truyền tĩnh mạch',
     'packaging_specifications': 'Túi 200ml', 'DVT': 'Túi', 'price': '116.633'},
    {'declaration_date': '18/04/2018', 'name': 'Xem chi tiết\n\n\n\n\nOlan 5',
     'active_ingredient_name': 'Olanzapin 5mg - 5mg', 'nd_dl': 'NULL', 'gplh_gpnk': 'VN-20287-17',
     'dosage_form': 'NULL', 'packaging_specifications': 'Hộp 3 vỉ x 10 Viên', 'DVT': 'Viên', 'price': '1.200'},
    {'declaration_date': '27/02/2018', 'name': 'Xem chi tiết\n\n\n\n\nBenzylpenicillin sodium Inj',
     'active_ingredient_name': 'Benzylpenicilin (dưới dạng Benzylpenicilin natri) 1.000.000 IU',
     'nd_dl': '1.000.000 IU', 'gplh_gpnk': 'VN-20522-17', 'dosage_form': 'NULL',
     'packaging_specifications': 'Hộp 50 lọ', 'DVT': 'Lọ', 'price': '1.700'},
    {'declaration_date': '21/05/2018', 'name': 'Xem chi tiết\n\n\n\n\nCelofen 100',
     'active_ingredient_name': 'Celecoxib 100mg', 'nd_dl': '100mg', 'gplh_gpnk': 'VN-20176-16', 'dosage_form': 'NULL',
     'packaging_specifications': 'Hộp 3 vỉ x 10 Viên', 'DVT': 'Viên', 'price': '1.700'},
    {'declaration_date': '14/11/2017', 'name': 'Xem chi tiết\n\n\n\n\nPantin 40',
     'active_ingredient_name': 'Pantoprazole (dưới dạng pantoprazol natri sesquihydrat) 40mg', 'nd_dl': 'NULL',
     'gplh_gpnk': 'VN-19184-15', 'dosage_form': 'NULL', 'packaging_specifications': 'Hộp 3 vỉ x 10 Viên',
     'DVT': 'Viên', 'price': '2.000'}, {'declaration_date': '27/02/2018', 'name': 'Xem chi tiết\n\n\n\n\nRedpharkit',
                                        'active_ingredient_name': 'Rabeprazole Sodium; Ornidazole; Clarithromycin',
                                        'nd_dl': '20mg/500mg/ 250mg', 'gplh_gpnk': 'VN-14839-12',
                                        'dosage_form': 'NULL',
                                        'packaging_specifications': 'Hộp 7 vỉ x 6 Viên (mỗi loại 2 Viên)',
                                        'DVT': 'Kit', 'price': '4.840'},
    {'declaration_date': '27/02/2018', 'name': 'Xem chi tiết\n\n\n\n\nSerapid',
     'active_ingredient_name': 'Flunarizine (dưới dạng Flunarizine HCl) 5mg', 'nd_dl': 'NULL',
     'gplh_gpnk': 'VN-18647-15', 'dosage_form': 'NULL', 'packaging_specifications': 'Hộp 6 vỉ x 10 Viên',
     'DVT': 'Viên', 'price': '825'}, {'declaration_date': '17/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nDloe 4',
                                      'active_ingredient_name': 'Ondansetron (dưới dạng Ondansetron hydrochloride dihydrate) 4mg/2ml',
                                      'nd_dl': '4mg/2ml', 'gplh_gpnk': 'VN-16669-13', 'dosage_form': 'Dung dịch tiêm',
                                      'packaging_specifications': 'Hộp 5 vỉ x 5 ống 2ml', 'DVT': 'Ống',
                                      'price': '30.000'},
    {'declaration_date': '25/09/2020', 'name': 'Xem chi tiết\n\n\n\n\nBru-cod',
     'active_ingredient_name': 'Cefpodoxim (dưới dạng Cefpodoxim proxetil)  50mg/5ml', 'nd_dl': '50mg/5ml',
     'gplh_gpnk': 'VN-16641-13', 'dosage_form': 'Bột pha hỗn dịch uống', 'packaging_specifications': 'Hộp 1 lọ',
     'DVT': 'Lọ', 'price': '25.100'},
    {'declaration_date': '17/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nBudesonide Teva 0,5mg/2ml',
     'active_ingredient_name': 'Budesonide', 'nd_dl': '0,5mg/2ml', 'gplh_gpnk': 'VN-15282-12',
     'dosage_form': 'Hỗn dịch khí dung', 'packaging_specifications': 'Hộp 30 ống 2ml', 'DVT': 'Ống',
     'price': '12.950'}, {'declaration_date': '29/11/2019', 'name': 'Xem chi tiết\n\n\n\n\nBriozcal',
                          'active_ingredient_name': 'Calci (dưới dạng Calci carbonat 1,25g) 500mg; Vitamin D3 125IU',
                          'nd_dl': '500mg, 125IU', 'gplh_gpnk': 'VN-22339-19', 'dosage_form': 'Viên nén bao phim',
                          'packaging_specifications': 'Hôp 3 vỉ x 10 viên', 'DVT': 'Viên', 'price': '3.759'},
    {'declaration_date': '31/08/2020', 'name': 'Xem chi tiết\n\n\n\n\nTorfin-50',
     'active_ingredient_name': 'Sildenafil (dưới dạng Sildenafil citrat) 50mg', 'nd_dl': '50 mg',
     'gplh_gpnk': 'VN-17231-13', 'dosage_form': 'Viên nén bao phim', 'packaging_specifications': 'Hộp 1 vỉ x 4 viên',
     'DVT': 'Viên', 'price': '6.000'},
    {'declaration_date': '05/11/2020', 'name': 'Xem chi tiết\n\n\n\n\nAxcel Loratadine  Tablet',
     'active_ingredient_name': 'loratadine', 'nd_dl': '10mg', 'gplh_gpnk': 'VN-21048-18', 'dosage_form': 'Viên nén',
     'packaging_specifications': 'Hộp 10 vỉ x 10 viên', 'DVT': 'Viên', 'price': '1.800'},
    {'declaration_date': '05/10/2020',
     'name': 'Xem chi tiết\n\n\n\n\nCKDCipol-N 25mg (Đóng gói và xuất xưởng bởi: Chong Kun Dang Pharmaceutical Corp., đ/c: 797-48 Manghyang-ro, Seonggeo-eup, Seobuk-gu, Choenan-si, Chungcheongnam-do, Repubic of Korea)',
     'active_ingredient_name': 'Cyclosporin 25mg', 'nd_dl': 'NULL', 'gplh_gpnk': 'VN-18193-14',
     'dosage_form': 'Viên nang mềm', 'packaging_specifications': 'Hộp 10 vỉ x 5 viên', 'DVT': 'Viên',
     'price': '13.000'},
    {'declaration_date': '22/10/2020', 'name': 'Xem chi tiết\n\n\n\n\nPiperacillin/ Tazobactam Kabi 4g/0,5g',
     'active_ingredient_name': 'Piperacilin, Tazobactam', 'nd_dl': '4g Piperacillin; 0,5g Tazobactam',
     'gplh_gpnk': 'VN-13544-11', 'dosage_form': 'Bột pha dung dịch tiêm truyền',
     'packaging_specifications': 'Hộp 1 lọ, hộp 10 lọ', 'DVT': 'Lọ', 'price': '105.000'},
    {'declaration_date': '27/02/2020', 'name': 'Xem chi tiết\n\n\n\n\nPrimolut N',
     'active_ingredient_name': 'Norethisterone 5mg', 'nd_dl': '5mg', 'gplh_gpnk': 'VN-19016-15',
     'dosage_form': 'Viên nén', 'packaging_specifications': 'Hộp 3 vỉ x 10 viên', 'DVT': 'Viên', 'price': '1.484'}
]

b = [
    {'declaration_date': '05/12/2017', 'status': 'Đã rà soát, không có văn bản', 'petition': '',
     'name': 'Hoàn quy tỳ TW3',
     'hc_name': 'Mỗi hoàn mềm 8g chứa: Bạch linh 0,62g; Bạch truật 0,62g; Đương quy 0,62g; Hoàng kỳ 0,62g; Đảng sâm 0,31g; Long nhãn 0,31g; Táo nhân 0,31g; Đại táo 0,30g; Viễn trí 0,15g; Cam thảo 0,09g; Mộc hương 0,05g',
     'nd_hl': '', 'gplh_gpnk': 'VD-25814-16', 'dosage_form': 'Hoàn mềm',
     'packaging_specifications': 'Hộp 6 hoàn x 8g; Hộp 10 hoàn x 8g', 'DVT': 'hoàn', 'price': '6,000'},
    {'declaration_date': '03/02/2017', 'status': 'Đã rà soát, không có văn bản', 'petition': '',
     'name': 'Hoàn thập toàn đại bổ TW3',
     'hc_name': 'Mỗi viên hoàn mềm 8g chứa: Đảng sâm 0,60g; Thục địa 0,60g; Bạch linh 0,41g; Bạch thược 0,41g; Bạch truật 0,41g; Đương quy 0,41g; Hoàng kỳ 0,41g; Xuyên khung 0,31g; Cam thảo 0,12g; Quế nhục 0,12g',
     'nd_hl': '', 'gplh_gpnk': 'VD-26304-17', 'dosage_form': 'Viên hoàn mềm',
     'packaging_specifications': 'Hộp 06 hoàn x 8g; Hộp 10 hoàn x 8g', 'DVT': 'hoàn', 'price': '5,775'},
    {'declaration_date': '10/05/2016', 'status': 'Đã rà soát, không có văn bản', 'petition': '',
     'name': 'Hoàn lục vị TW3',
     'hc_name': 'Mỗi hoàn mềm 8g chứa: Thục địa 1,344g; Hoài sơn 0,672g; Sơn thù 0,672g; Bạch linh 0,504g; Mẫu đơn bì 0,504g; Trạch tả 0,504g',
     'nd_hl': '', 'gplh_gpnk': 'VD-24300-16', 'dosage_form': 'Hoàn mềm',
     'packaging_specifications': 'Hộp 6 hoàn, 10 hoàn x 8g', 'DVT': 'hoàn', 'price': '5,500'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8555e/QLD-GT\n\n23/07/2024',
     'name': 'A.T Pantoprazol Tab', 'hc_name': 'Pantoprazol\n(dưới dạng pantoprazol natri sesquihydrat)',
     'nd_hl': '40mg', 'gplh_gpnk': '893110278823', 'dosage_form': 'Viên nén bao phim tan trong ruột',
     'packaging_specifications': 'Hộp 2 vỉ, 3 vỉ, 5 vỉ, 10 vỉ x 10 viên; Hộp 1 chai x 30 viên, 60 viên, 100 viên',
     'DVT': 'viên', 'price': '2,600'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8558e/QLD-GT\n\n23/07/2024',
     'name': 'A.T Rosuvastatin 5', 'hc_name': 'Rosuvastatin (dưới dạng rosuvastatin calci)', 'nd_hl': '5mg',
     'gplh_gpnk': '893110276223', 'dosage_form': 'Viên nén bao phim',
     'packaging_specifications': 'Hộp 2 vỉ, 3 vỉ, 5 vỉ, 10 vỉ x 10 viên; Hộp 1 chai x 30 viên, 60 viên, 100 viên',
     'DVT': 'viên', 'price': '1,900'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8561e/QLD-GT\n\n23/07/2024',
     'name': 'A.T Rosuvastatin 20', 'hc_name': 'Rosuvastatin (dưới dạng rosuvastatin calci)', 'nd_hl': '20mg',
     'gplh_gpnk': '893110276123', 'dosage_form': 'Viên nén bao phim',
     'packaging_specifications': 'Hộp 2 vỉ, 3 vỉ, 5 vỉ, 10 vỉ x 10 viên; Hộp 1 chai x 30 viên, 60 viên, 100 viên',
     'DVT': 'viên', 'price': '6,800'},
    {'declaration_date': '30/06/2024', 'status': '', 'petition': '', 'name': 'A.T Dexketoprofen 50mg/2ml',
     'hc_name': 'Dexketoprofen (dưới dạng Dexketoprofen trometamol)', 'nd_hl': '50mg/2ml', 'gplh_gpnk': '893110361424',
     'dosage_form': 'Dung dịch tiêm, tiêm truyền', 'packaging_specifications': 'Hộp 5 ống, 10 ống, 20 ống x 2ml',
     'DVT': 'ống', 'price': '18,000'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8196e/QLD-GT\n\n12/07/2024',
     'name': 'Adverlex 250 Cap', 'hc_name': 'Cephalexin (dưới dạng cephalexin monohydrat) 250mg', 'nd_hl': '250mg',
     'gplh_gpnk': '893110202123', 'dosage_form': 'Viên nang cứng',
     'packaging_specifications': 'Hộp 01 vỉ x 10 viên; Hộp 03 vỉ x 10 viên;\nHộp 10 vỉ x 10 viên', 'DVT': 'viên',
     'price': '1,260'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8556e/QLD-GT\n\n23/07/2024',
     'name': 'A.T Pantoprazol', 'hc_name': 'Pantoprazol (dưới dạng Pantoprazol natri sesquihydrat)', 'nd_hl': '40mg',
     'gplh_gpnk': '893110147924', 'dosage_form': 'Bột đông khô pha tiêm',
     'packaging_specifications': 'Hộp 1 lọ thuốc + 1 ống dung môi 10ml; Hộp 3 lọ thuốc + 3 ống dung môi 10ml; Hộp 5 lọ thuốc + 5 ống dung môi 10ml',
     'DVT': 'lọ', 'price': '31,000'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8199e/QLD-GT\n\n12/07/2024',
     'name': 'Adverlex 750 Cap', 'hc_name': 'Cephalexin (dưới dạng Cephalexin monohydrat)', 'nd_hl': '750mg',
     'gplh_gpnk': '893110236024', 'dosage_form': 'Viên nang cứng',
     'packaging_specifications': 'Hộp 1 vỉ x 10 viên, Hộp 3 vỉ x 10 viên, Hộp 10 vỉ x 10 viên, vỉ Al/Al; Hộp 1 vỉ x 10 viên, Hộp 3 vỉ x 10 viên, Hộp 10 x 10 viên, vỉ Al/PVC',
     'DVT': 'viên', 'price': '4,000'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8198e/QLD-GT\n\n12/07/2024',
     'name': 'Ceftriaxon TFI 500 mg', 'hc_name': 'Ceftriaxon (dưới dạng Ceftriaxon natri)', 'nd_hl': '500 mg',
     'gplh_gpnk': '893110371124', 'dosage_form': 'Bột pha tiêm', 'packaging_specifications': 'Hộp 1 lọ, Hộp 10 lọ',
     'DVT': 'lọ', 'price': '17,000'},
    {'declaration_date': '30/06/2024', 'status': '', 'petition': '', 'name': 'Difentab 20', 'hc_name': 'Baclofen',
     'nd_hl': '20mg', 'gplh_gpnk': '893110254024', 'dosage_form': 'Viên nén',
     'packaging_specifications': 'Hộp 3 vỉ, 5 vỉ, 10 vỉ x 10 viên (vỉ Alu –PVC hoặc Alu –Alu);\nChai 50 viên, Chai 100 viên, Chai 200 viên',
     'DVT': 'viên', 'price': '3,850'},
    {'declaration_date': '30/06/2024', 'status': 'Có văn bản kiến nghị', 'petition': '8194e/QLD-GT\n\n12/07/2024',
     'name': 'Adverlex 500 Tab', 'hc_name': 'Cephalexin (dưới dạng cephalexin monohydrat)\xa0\n500mg', 'nd_hl': '500mg',
     'gplh_gpnk': '893110202223', 'dosage_form': 'Viên nén bao phim',
     'packaging_specifications': 'Hộp 1 vỉ x 10 viên; Hộp 03 vỉ x 10 viên; Hộp 10\nvỉ x 10 viên', 'DVT': 'viên',
     'price': '2,750'}, {'declaration_date': '30/06/2024', 'status': '', 'petition': '', 'name': 'Goodcam',
                         'hc_name': 'Vitamin B1 15mg; Vitamin B2 15mg; Vitamin B5 25mg; Vitamin B6 10mg; Vitamin PP 50mg',
                         'nd_hl': '15mg, 15mg, 25mg, 10mg, 50mg', 'gplh_gpnk': '893100288824',
                         'dosage_form': 'Viên nén bao phim',
                         'packaging_specifications': 'Hộp 3 vỉ, Hộp 5 vỉ, Hộp 6 vỉ, Hộp 10 vỉ x 10 viên; Chai 60 viên, Chai 100 viên, Chai 200 viên',
                         'DVT': 'viên', 'price': '4,900'},
    {'declaration_date': '30/06/2024', 'status': '', 'petition': '', 'name': 'Amaloris 5mg/10mg',
     'hc_name': 'Atorvastatin, Amlodipine',
     'nd_hl': 'Atorvastatin (dưới dạng Atorvastatin calcium trihydrate 10,85mg) 10mg , Amlodipine (dưới dạng Amlodipine besilate 6,94mg) 5mg',
     'gplh_gpnk': '383110181023', 'dosage_form': 'Viên nén bao phim', 'packaging_specifications': 'Hộp 3 vỉ x 10 viên',
     'DVT': 'viên', 'price': '9,000'}]
